/* System Design — the reader.
   No dependencies, no build step of its own. content.js is generated by
   build.mjs and sets window.BOOK; everything below just renders it.

   Routes live in the hash so a lesson can be linked and the back button works:
     #/                       the title page
     #/api-design             a chapter's contents
     #/api-design/3           lesson 3 of that chapter  */

const BOOK = window.BOOK;
const $ = (s) => document.querySelector(s);
const STORE = 'systemdesign.book';

/* ── flatten once: every lesson in reading order, so previous/next can cross
      a chapter boundary without special-casing it ── */
const FLAT = [];
BOOK.chapters.forEach((c, ci) => {
  FLAT.push({ kind: 'chapter', ci, chapter: c });
  c.lessons.forEach((l, li) => FLAT.push({ kind: 'lesson', ci, li, chapter: c, lesson: l }));
});
const indexOf = (ci, li) =>
  FLAT.findIndex(x => x.ci === ci && (li == null ? x.kind === 'chapter' : x.li === li));

/* ── state ── */
const saved = load();
let theme = saved.theme || null;
if (theme) document.documentElement.dataset.theme = theme;

/* ── cover ── */
$('#coverTitle').innerHTML = BOOK.title.replace(/\s+/, '<br>');
$('#coverKicker').textContent = BOOK.kicker || '';
$('#coverByline').textContent =
  `${BOOK.chapters.length} chapter${BOOK.chapters.length === 1 ? '' : 's'} · ` +
  `${BOOK.chapters.reduce((s, c) => s + c.lessons.length, 0)} lessons`;

if (saved.route && saved.route !== '#/') {
  const at = routeLabel(saved.route);
  if (at) {
    const b = $('#resumeBtn');
    b.hidden = false;
    b.textContent = 'Resume — ' + at;
    b.onclick = () => open(saved.route);
  }
}

function routeLabel(hash) {
  const p = parse(hash);
  if (!p || p.kind === 'title') return null;
  const c = BOOK.chapters[p.ci];
  if (!c) return null;
  return p.kind === 'chapter' ? c.title : `${c.title}, lesson ${c.lessons[p.li].n}`;
}

/* ── open / close ── */
$('#book').onclick = () => open();
$('#book').onkeydown = (e) => {
  if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); }
};
$('#openBtn').onclick = () => open();

function open(hash) {
  const book = $('#book');
  book.classList.add('opening');
  setTimeout(() => {
    $('#shelf').hidden = true;
    $('#app').hidden = false;
    book.classList.remove('opening');
    if (hash) location.hash = hash;
    else route();
    $('#reading').focus({ preventScroll: true });
  }, 420);
}

$('#closeBtn').onclick = () => {
  $('#app').hidden = true;
  $('#shelf').hidden = false;
  window.scrollTo(0, 0);
};
$('#homeBtn').onclick = () => { location.hash = '#/'; };

/* ── contents sidebar ── */
$('#tocToggle').onclick = () => {
  const f = $('.frame'), on = f.classList.toggle('collapsed');
  $('#tocToggle').setAttribute('aria-expanded', String(!on));
};

$('#themeBtn').onclick = () => {
  // Three states in, two states out: whatever the page looks like now, flip it.
  const dark = document.documentElement.dataset.theme
    ? document.documentElement.dataset.theme === 'dark'
    : matchMedia('(prefers-color-scheme: dark)').matches;
  theme = dark ? 'light' : 'dark';
  document.documentElement.dataset.theme = theme;
  save();
};

function renderToc(active) {
  $('#toc').innerHTML =
    '<h2>Contents</h2>' +
    BOOK.chapters.map((c, ci) => `
      <div class="toc-ch">
        <button data-ch="${ci}"><span class="num">${c.numeral}</span><span>${c.title}</span></button>
        <ol>${c.lessons.map((l, li) => `
          <li><button data-ch="${ci}" data-l="${li}"
            ${active && active.ci === ci && active.li === li ? 'aria-current="true"' : ''}>
            <span class="n">${String(l.n).padStart(2, '0')}</span><span>${l.title}</span>
          </button></li>`).join('')}
        </ol>
      </div>`).join('');

  $('#toc').querySelectorAll('button').forEach(b => b.onclick = () => {
    const ci = +b.dataset.ch;
    location.hash = b.dataset.l == null
      ? `#/${BOOK.chapters[ci].id}`
      : `#/${BOOK.chapters[ci].id}/${BOOK.chapters[ci].lessons[+b.dataset.l].n}`;
    if (innerWidth <= 940) $('.frame').classList.add('collapsed');
  });
}

/* ── routing ── */
function parse(hash) {
  const m = (hash || location.hash).replace(/^#\/?/, '').split('/').filter(Boolean);
  if (!m.length) return { kind: 'title' };
  const ci = BOOK.chapters.findIndex(c => c.id === m[0]);
  if (ci < 0) return { kind: 'title' };
  if (m.length === 1) return { kind: 'chapter', ci };
  const li = BOOK.chapters[ci].lessons.findIndex(l => String(l.n) === m[1]);
  return li < 0 ? { kind: 'chapter', ci } : { kind: 'lesson', ci, li };
}

function route() {
  const p = parse();
  if (p.kind === 'title') titlePage();
  else if (p.kind === 'chapter') chapterPage(p.ci);
  else lessonPage(p.ci, p.li);
  save();
}

// Any hash change means the reader should be on screen. Without this, pasting
// a lesson link while the cover is showing renders the page behind a hidden
// element - the route runs, the title bar updates, and you still see the book.
addEventListener('hashchange', () => {
  if ($('#app').hidden) { $('#shelf').hidden = true; $('#app').hidden = false; }
  route();
});

/* ── views ── */
function titlePage() {
  renderToc(null);
  $('#crumb').textContent = '';
  $('#reading').innerHTML = `
    <div class="title-page">
      <p class="kick">${BOOK.kicker || ''}</p>
      <h1>${BOOK.title}</h1>
      <p class="sub">${BOOK.subtitle || ''}</p>
      <div class="rule"></div>
      <div class="parts">
        ${BOOK.chapters.map((c, ci) => `
          <button data-ch="${ci}">
            <span class="rn">${c.numeral}</span>
            <span>${c.title}</span>
            <span class="cnt">${c.lessons.length} lessons</span>
          </button>`).join('')}
      </div>
      <p class="colophon">${BOOK.colophon || ''}
        <span>Typeset ${BOOK.built} · ${BOOK.chapters.reduce((s, c) => s + c.lessons.reduce((t, l) => t + l.words, 0), 0).toLocaleString('en-US')} words</span>
      </p>
    </div>`;
  bindJumps();
  scrollTop();
}

function chapterPage(ci) {
  const c = BOOK.chapters[ci];
  renderToc(null);
  $('#crumb').textContent = `Chapter ${c.numeral}`;
  $('#reading').innerHTML = `
    <div class="chapter-page">
      <p class="numeral">${c.numeral}</p>
      <h1>${c.title}</h1>
      <p class="blurb">${c.blurb || ''}</p>
      <ol>
        ${c.lessons.map((l, li) => `
          <li><button data-ch="${ci}" data-l="${li}">
            <span class="n">${String(l.n).padStart(2, '0')}</span>
            <span>${l.title}</span>
            <span class="mins">${l.minutes} min</span>
          </button></li>`).join('')}
      </ol>
    </div>` + footNav(indexOf(ci, null));
  bindJumps();
  scrollTop();
}

function lessonPage(ci, li) {
  const c = BOOK.chapters[ci], l = c.lessons[li];
  renderToc({ ci, li });
  $('#crumb').textContent = `${c.title} · ${String(l.n).padStart(2, '0')}`;
  document.title = `${l.title} — ${BOOK.title}`;
  $('#reading').innerHTML = `
    <div class="runhead"><span>Chapter ${c.numeral} · ${c.title}</span><span>Lesson ${l.n}</span></div>
    <div class="opener">
      <p class="chapline">Lesson ${l.n}</p>
      <h1>${l.title}</h1>
      <p class="meta">${l.minutes} min read · ${l.words.toLocaleString('en-US')} words</p>
    </div>
    <article class="sheet prose">${l.html}</article>
    ${footNav(indexOf(ci, li))}`;
  bindJumps();
  scrollTop();
}

function footNav(at) {
  const prev = FLAT[at - 1], next = FLAT[at + 1];
  const label = (x) => x.kind === 'chapter'
    ? `Chapter ${x.chapter.numeral} · ${x.chapter.title}`
    : x.lesson.title;
  const href = (x) => x.kind === 'chapter'
    ? `#/${x.chapter.id}` : `#/${x.chapter.id}/${x.lesson.n}`;
  return `<nav class="footnav">
    ${prev ? `<button class="prev" data-go="${href(prev)}">
      <span class="dir">← Previous</span><span class="ttl">${label(prev)}</span></button>` : '<span></span>'}
    ${next ? `<button class="next" data-go="${href(next)}">
      <span class="dir">Next →</span><span class="ttl">${label(next)}</span></button>` : '<span></span>'}
  </nav>`;
}

function bindJumps() {
  $('#reading').querySelectorAll('[data-go]').forEach(b =>
    b.onclick = () => { location.hash = b.dataset.go; });
  $('#reading').querySelectorAll('[data-ch]').forEach(b =>
    b.onclick = () => {
      const ci = +b.dataset.ch;
      location.hash = b.dataset.l == null
        ? `#/${BOOK.chapters[ci].id}`
        : `#/${BOOK.chapters[ci].id}/${BOOK.chapters[ci].lessons[+b.dataset.l].n}`;
    });
  // Links the build step rewrote to in-book routes still need the sidebar and
  // scroll position updating, which hashchange handles for us.
  $('#reading').querySelectorAll('.offbook').forEach(s =>
    s.title = 'This file is not part of the book — open it from the project folder.');
}

// Turning to a new lesson should land at the top immediately. `scroll-behavior:
// smooth` is set globally for in-page anchors, so this has to opt out of it
// explicitly - otherwise every lesson change animates a long scroll.
function scrollTop() {
  window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
  document.documentElement.scrollTop = 0;
}

/* ── keyboard ── */
addEventListener('keydown', (e) => {
  if ($('#app').hidden) return;
  if (e.metaKey || e.ctrlKey || e.altKey) return;
  const tag = document.activeElement && document.activeElement.tagName;
  if (tag === 'INPUT' || tag === 'TEXTAREA') return;

  const at = (() => { const p = parse(); return p.kind === 'title' ? -1 : indexOf(p.ci, p.kind === 'lesson' ? p.li : null); })();
  if (e.key === 'ArrowRight' && at >= 0 && FLAT[at + 1]) {
    const n = FLAT[at + 1];
    location.hash = n.kind === 'chapter' ? `#/${n.chapter.id}` : `#/${n.chapter.id}/${n.lesson.n}`;
  }
  if (e.key === 'ArrowLeft' && at > 0) {
    const p = FLAT[at - 1];
    location.hash = p.kind === 'chapter' ? `#/${p.chapter.id}` : `#/${p.chapter.id}/${p.lesson.n}`;
  }
  if (e.key === 't') $('#tocToggle').click();
  if (e.key === 'Escape') location.hash = '#/';
});

/* ── remembering where you were ── */
function save() {
  try {
    localStorage.setItem(STORE, JSON.stringify({ route: location.hash || '#/', theme }));
  } catch { /* private window, or storage disabled - the book still works */ }
}
function load() {
  try { return JSON.parse(localStorage.getItem(STORE) || '{}'); }
  catch { return {}; }
}

/* If someone opens a deep link directly, skip the cover ceremony. */
if (location.hash && location.hash !== '#/') {
  $('#shelf').hidden = true;
  $('#app').hidden = false;
  route();
} else {
  route();
}
